server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: Ldy9290804
    url: jdbc:mysql://localhost:3306/exam_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## springboot 2.X
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB